version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      npm-production-dependencies:
        dependency-type: "production"
        update-types:
        - "minor"
        - "patch"
      npm-dev-dependencies:
        dependency-type: "development"
        update-types:
        - "minor"
        - "patch"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      go-dependencies:
        update-types:
        - "minor"
        - "patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      ci-dependencies:
        update-types:
        - "minor"
        - "patch"