// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function LoadStationFile() {
  return window['go']['main']['App']['LoadStationFile']();
}

export function SetSignal(arg1, arg2) {
  return window['go']['main']['App']['SetSignal'](arg1, arg2);
}
