// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {station} from '../models';

export function LoadStationFile():Promise<station.Definition>;
