name: Wails build

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

env:
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    name: Build
    strategy:
      matrix:
        build:
          - name: 'MarshalController'
            platform: 'windows/amd64'
            os: 'windows-latest'
    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build wails
        uses: dAppServer/wails-build-action@v2.2
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          go-version: '1.21'
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Create release tag
        id: create_release
        run: |
          TAG="v$(date +'%d%m%Y')-$(echo ${{ github.sha }} | cut -c1-8)"
          echo "Creating release tag $TAG"
          echo "::set-output name=tag::$TAG"
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./artifacts/**/*"
          generateReleaseNotes: true
          tag: ${{ steps.create_release.outputs.tag }}

